name: Workflow 2

on:
  workflow_run:
    workflows: ["Workflow 1"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use CRNUMBER from Workflow 1
        run: |
          echo "CRNUMBER from Workflow 1: ${{ github.event.workflow_run.outputs.build.crnumber }}"
