name: Workflow 2

on:
  workflow_run:
    workflows: ["Workflow 1"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download artifact from Workflow 1
        uses: actions/download-artifact@v3
        with:
          name: workflow1-output
          path: .

      - name: Use the output from Workflow 1
        run: |
          cat output.txt
