name: Workflow 2

on:
  push:
    branches:
      - master
  repository_dispatch:
    types: [trigger_workflow_2]
  #schedule:
    #- cron: '*/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Download CRNUMBER artifact
        uses: actions/download-artifact@v2
        with:
          name: crnumber-artifact

      - name: Use CRNUMBER
        run: |
          CRNUMBER=$(cat crnumber.txt)
          echo "CRNUMBER from artifact: $CRNUMBER"
      - name: Print CRNUMBER
        run: |
          echo "CRNUMBER from Workflow 1: ${{ github.event.client_payload.crnumber }}"
          echo "cr number from echo ${{ env.CRNUMBER }}"
          echo "its from secrets CRNUMBER=${{ secrets.CRNUMBER }}"
          env
        env:
          CRNUMBER: "${{ env.CRNUMBER }}"
