name: Workflow 1

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate output
        id: generate_output
        run: |
          echo "some output" > output.txt

      - name: Upload output as artifact
        uses: actions/upload-artifact@v3
        with:
          name: workflow1-output
          path: output.txt

      - name: Trigger Workflow 2
        uses: actions/github-script@v5
        with:
          script: |
            const workflow = await github.actions.listRepoWorkflows({
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            const workflowId = workflow.data.workflows.find(w => w.name === "Workflow 2").id;
            await github.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id
