name: Workflow 1

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate CRNUMBER
        id: generate_output
        run: |
          echo "CRNUMBER=12345" >> $GITHUB_ENV
          echo "::set-output name=crnumber::12345"

      - name: Debug Outputs
        run: echo "CRNUMBER is set to ${{ steps.generate_output.outputs.crnumber }}"
    outputs:
      crnumber: ${{ steps.generate_output.outputs.crnumber }}
