name: Workflow 2

on:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download artifact from Workflow 1
        uses: actions/download-artifact@v3
        with:
          name: workflow1-output
          path: .

      - name: List files in the current directory
        run: |
          ls -al

      - name: Use the output from Workflow 1
        run: |
          cat output.txt
