name: Workflow 1

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate CRNUMBER
        id: generate_output
        run: |
          echo "CRNUMBER=12345" > crnumber.txt

      - name: Upload CRNUMBER as artifact
        uses: actions/upload-artifact@v3
        with:
          name: crnumber
          path: crnumber.txt
